In [15]:
from keras.models import model_from_json
import numpy as np
import pandas as pd

In [16]:
train = pd.read_csv('time_series_train_data.csv')
test = pd.read_csv('time_series_test_data.csv')

In [17]:
train

Date and time          y         x1         x2         x3
0       01-01-2020 00:00  56.972500        NaN        NaN        NaN
1       01-01-2020 00:10  56.695001  56.972500        NaN        NaN
2       01-01-2020 00:20  56.640000  56.695001  56.972500        NaN
3       01-01-2020 00:30  56.432500  56.640000  56.695001  56.972500
4       01-01-2020 00:40  56.169998  56.432500  56.640000  56.695001
...                  ...        ...        ...        ...        ...
311913  31-12-2020 23:10  50.830000  50.880000  51.015000  51.052500
311914  31-12-2020 23:20  50.792500  50.830000  50.880000  51.015000
311915  31-12-2020 23:30  50.742500  50.792500  50.830000  50.880000
311916  31-12-2020 23:40  50.799999  50.742500  50.792500  50.830000
311917  31-12-2020 23:50  50.772500  50.799999  50.742500  50.792500

[311918 rows x 5 columns]

In [18]:
test

Date and time          y         x1         x2         x3
0       01-01-2021 00:00  17.442500        NaN        NaN        NaN
1       01-01-2021 00:10  18.220000  17.442500        NaN        NaN
2       01-01-2021 00:20  18.230000  18.220000  17.442500        NaN
3       01-01-2021 00:30  17.485000  18.230000  18.220000  17.442500
4       01-01-2021 00:40  17.785000  17.485000  18.230000  18.220000
...                  ...        ...        ...        ...        ...
142887  16-06-2021 07:40  57.497499  56.885000  56.445000  56.434210
142888  16-06-2021 07:50  57.591667  57.497499  56.885000  56.445000
142889  16-06-2021 08:00  57.375001  57.591667  57.497499  56.885000
142890  16-06-2021 08:10  57.239474  57.375001  57.591667  57.497499
142891  16-06-2021 08:20  56.509999  57.239474  57.375001  57.591667

[142892 rows x 5 columns]

In [19]:
x_train = train.iloc[3:,2:]
y_train = train.iloc[3:,1:2]

x_test = test.iloc[3:,2:]
y_test =test.iloc[3:,1:2]

In [20]:
n_samples = x_train.values.shape[0]
n_timestamps = 1
n_features = x_train.values.shape[1]

x_train = x_train.values.reshape(n_samples, n_timestamps, n_features)

In [21]:
x_test = x_test.values.reshape(x_test.shape[0], 1, x_test.shape[1])

In [22]:
#loading Model

file = open('lstm_model.json', 'r')
loaded  = file.read()
file.close()

lstm_model = model_from_json(loaded)
lstm_model.load_weights("lstm_model.h5")

In [23]:
train_pred=lstm_model.predict(x_train)
train_pred

9748/9748 [==============================] - 12s 1ms/step


array([[56.783363],
       [56.589478],
       [56.384315],
       ...,
       [50.959877],
       [50.90689 ],
       [50.967033]], dtype=float32)

In [24]:
test_pred=lstm_model.predict(x_test)
test_pred

   1/4466 [..............................] - ETA: 2:13

4466/4466 [==============================] - 5s 1ms/step


array([[18.085152],
       [17.355629],
       [17.896046],
       ...,
       [57.448433],
       [57.407597],
       [57.324112]], dtype=float32)

In [25]:
lstm_model.predict([[[17.850,17.485,18.23]]])

1/1 [==============================] - 0s 41ms/step


array([[17.969482]], dtype=float32)